sudo: false
language: python
cache: pip

matrix:
    include:
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5

script:
  - py.test --cov-report=term-missing --cov-report=xml --cov=snake/ tests/
  
install:
  - pip install codecov tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
