language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

script:
  - tox -e $TOX_ENV
  
install:
  - pip install codecov tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
