language: python
sudo: false
python:
      - "2.7"
          
env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34

script:
  - tox -e $TOX_ENV

before_install:
  - pip install codecov

after_success:
  - codecov -e TOX_ENV
