language: python

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34

script:
  - tox -e $TOX_ENV
  
install:
  - pip install codecov tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
